### ISSUE TITLE
TXo crashes when sending multiple cv outs

### ISSUE THREAD

**Issue by dead-asleep** [miotislucifugis/Telex_teensy4#1]
Teletype running firmware v 5.0.0 00F5FD2
TXo running on teensy 4.0 flashed at 150MHz and 396MHz with same results

Getting a crash scenario while sending CV to all of the outputs simultaneously.

To repro:
set metro to 120 BPM in live mode `M BPM 120`

add this line to the metro script `L 1 4: TO.CV I VV RND 1000`

TXo will freeze up / crash after a few seconds and anything on the i2c bus becomes unresponsive. 

Another thing worth mentioning is that when I compiled this firmware (as well as the TXi firmware) I received this error in the console:

TELEXo_T4: In function 'void setup()':
/Users/johndoe/workspace/Telex_teensy4/TELEXo_T4/TELEXo_T4.ino:150:30: warning: invalid conversion from 'void (*)(size_t) {aka void (*)(unsigned int)}' to 'void (*)(int)' [-fpermissive]
   Wire.onReceive(receiveEvent);
                              ^
In file included from /Users/johndoe/workspace/Telex_teensy4/TELEXo_T4/TELEXo_T4.ino:19:0:
/Users/johndoe/Documents/Arduino/libraries/teensy4_i2c/src/i2c_driver_wire.h:92:17: note:   initializing argument 1 of 'void I2CDriverWire::onReceive(void (*)(int))'
     inline void onReceive(void (* function)(int len)) {
                 ^
Memory Usage on Teensy 4.0:
  FLASH: code:81656, data:782508, headers:8920   free for files:1158532
   RAM1: variables:117344, code:79848, padding:18456   free for local variables:308640
   RAM2: variables:12384  free for malloc/new:511904

Curious if you get the same error when you compile?

**Comment by miotislucifugis** [comment]
sorry for the late reply.  I just got around to testing this and I cannot recreate your problem.   I even jacked up the BPM to 300 and let it run for 10-15 minutes with no issue.   

based on the console messages and the problem you are experiencing, I would guess that you didnt properly install the t4 i2c library.   (tho' It looks like it is there judging from the console messages)    I haven't reflashed the teensy, but i don't recall getting those.  It could be that since they are are drop-in compatible, arduino is defaulting to Wire when it has issues with t4i2c callbacks.  I had similar experiences w/ freezing when I first tried converting this code for T4 and was using wire... simple things would work, but if TXO was doing multiple things at once and at faster rates, it would hang.

(**Edit   I just tried and I DO get those error messages when I compile in arduino.IDE ... but it still compiles successfully)

I just added a .hex file (in the "build" folder, in the TXO fdirectory)  so you can try that to rule out arduino/software issues.

**Comment by miotislucifugis** [comment]
closing this unless others are having the same problem
